/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFramePrincipal.java
 *
 * Created on 20/04/2012, 12:03:11 PM
 */

package otelo.Hexagonal;

import java.awt.BorderLayout;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author cliente
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /** Creates new form JFramePrincipal */
    public JFramePrincipal() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.setLocationRelativeTo(null);
        // <editor-fold defaultstate="collapsed" desc="Inicializacion de hilos y GUI">
        jLabelJug1.setText("Jugador 1 (Maq - Facil)");
        jLabelJug2.setText("Jugador 2 (Maq - Facil)");
        otheHex = new OthelloHexagonal(6, OthelloHexagonal.FACIL, OthelloHexagonal.FACIL);
        conf = new JDialogConfiguracion(this, false);
        juegoTerm = otheHex.isFin();
        cargarPanelJuego();
        TimerTask tarea = new TimerTask() {
            @Override
            public void run() {
                mostrarInformacion();
                nuevoJuego();
                repaint();
            }
        };
        Timer timer = new Timer();
        timer.schedule(tarea, 0, 200);
        // </editor-fold>
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneSuperior = new javax.swing.JSplitPane();
        jPanelResultados = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFichasTotales = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelFichasNegras = new javax.swing.JLabel();
        jLabelJug2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelIcon2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelFichasBlancas = new javax.swing.JLabel();
        jLabelJug1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelIcon1 = new javax.swing.JLabel();
        jPanelJuego = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Otelo Hexagonal");

        jSplitPaneSuperior.setDividerLocation(200);
        jSplitPaneSuperior.setOneTouchExpandable(true);

        jPanelResultados.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMACION DEL JUEGO:"));

        jLabel1.setText("Fichas Totales:");

        jLabelFichasTotales.setText("# fichas");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("JUGADOR 2:"));

        jLabel4.setText("Negras");

        jLabelFichasNegras.setText("# fichas");

        jLabelJug2.setText("Jugador 2:");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);

        jLabelIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/computer.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJug2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabelFichasNegras))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJug2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFichasNegras)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabelIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("JUGADOR 1:"));

        jLabel5.setText("Blancas");

        jLabelFichasBlancas.setText("# fichas");

        jLabelJug1.setText("Jugador 1:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);

        jLabelIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/computer.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabelFichasBlancas)))
                    .addComponent(jLabelJug1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJug1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFichasBlancas)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelFichasTotales))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFichasTotales)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
        jPanelResultados.setLayout(jPanelResultadosLayout);
        jPanelResultadosLayout.setHorizontalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelResultadosLayout.setVerticalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPaneSuperior.setLeftComponent(jPanelResultados);

        jPanelJuego.setLayout(new java.awt.BorderLayout());
        jSplitPaneSuperior.setRightComponent(jPanelJuego);

        jMenuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ipod.png"))); // NOI18N
        jMenuArchivo.setMnemonic('r');
        jMenuArchivo.setText("Archivo");

        jMenuItemNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.png"))); // NOI18N
        jMenuItemNuevo.setMnemonic('n');
        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemNuevo);

        jMenuBar1.add(jMenuArchivo);

        jMenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        jMenuAyuda.setMnemonic('y');
        jMenuAyuda.setText("Ayuda");

        jMenuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flag_red.png"))); // NOI18N
        jMenuItemSalir.setMnemonic('s');
        jMenuItemSalir.setText("Reglas del Juego");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemSalir);

        jMenuBar1.add(jMenuAyuda);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/attach.png"))); // NOI18N
        jMenu1.setText("Acerca del Juego");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/script.png"))); // NOI18N
        jMenuItem1.setText("Historia");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/information.png"))); // NOI18N
        jMenuItem2.setText("Creditos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        conf.setVisible(true);
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed



        JOptionPane.showMessageDialog(this, "REGLAS DEL JUEGO\n" +


                "1.- Un jugador puede colocar una ficha en una casilla vacía sólo si es\n" +
                "adyacente a una ficha del contrario y está en línea con una ficha\n" +
                "propia, verticalmente, horizontalmente o diagonalmente. Las fichas\n" +
                "esposadas de esta manera son vueltas boca abajo y pasan a manos del contrario.\n"+
                "2.- Cuando una ficha ha sido emplazada, ya no se moverá de su casilla,\n"+
                "pero puede ser volteada varias veces, según un jugador u otro la reclame.\n"+
                "3.- Si jugando una ficha cierra las esposas en dos líneas de fichas contrarias,\n"+
                "ambas fichas dan la vuelta.\n"+
                "4.- Si un jugador no puede jugar una ficha adyacente a la del contrario\n"+
                "y en línea con la suya propia, debe pasar. Deberá pasar hasta que pueda jugar.\n"+
                "De todas maneras, esta situación no corre peligro de eternizarse porque cada\n"+
                "jugador tiene un numero determinado de turnos para tirar.","Reglas del Juego",1);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JOptionPane.showMessageDialog(this, "Otelo es un juego abstracto territorial para 2 jugadores, creado por \n" +
                "el japonés Goro Hasegawa en 1971.\n" +
                "Goro se inspiró en la obra de Shakespeare del mismo nombre y en \n" +
                "un juego inglés del siglo XIX, el Reversi. Ambos juegos son muy\n" +
                "similares, por lo que muchas veces se le llama al Otelo, Reversi.\n" +
                "El origen de ambos puede estar en un juego milenario de Tibet, el Ming Mang. \n"+
                "Se trata de un juego muy sencillo y rápido de jugar, que crea interés\n"+
                "entre los programadores, por lo que podemos encontrar miles de\n"+
                "versiones para jugar on-line en internet.","Historia",1);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
  JOptionPane.showMessageDialog(this, "INTELIGENCIA ARTIFICIAL\n" +
                "UNMSM - FISI - 2012-II\n" +
                "Integrantes:\n" +
                "*    Hualpa Espinoza, Jaime\n" +
                "*    Yaringaño Malpartida, Paul\n" +
                "*    Huañac Azurza, Andres\n" ,"Creditos",1);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // <editor-fold defaultstate="collapsed" desc="Actualizadores del panel de dibujo">
    private void cargarPanelJuego(){
        jpaneJuegoHexagonal = new JPanelOtelo(otheHex);
        jpaneJuegoHexagonal.setSize(jPanelJuego.getSize());
        jPanelJuego.add(jpaneJuegoHexagonal,BorderLayout.CENTER);
        jPanelJuego.repaint();
    }

    private void mostrarInformacion(){
        jLabelFichasNegras.setText(""+otheHex.cantN()+ " Fichas");
        jLabelFichasBlancas.setText(""+otheHex.cantB()+ " Fichas");
        int cant = otheHex.cantB()+otheHex.cantN();
        jLabelFichasTotales.setText(""+ cant + " Fichas");
        if(otheHex.isFin()){
            String most = "";
            if(otheHex.cantB()>otheHex.cantN() && !juegoTerm)
                most = "No es posible realizar mas movimientos, las fichas Blancas Ganaron";
            if(otheHex.cantB()<otheHex.cantN() && !juegoTerm)
                most = "No es posible realizar mas movimientos, las fichas Negras Ganaron";
            if(otheHex.cantB()==otheHex.cantN() && !juegoTerm)
                most = "No es posible realizar mas movimientos, juego empatado";
            if (!juegoTerm)
                JOptionPane.showMessageDialog(null, most);
            juegoTerm = true;
        }
    }

    private void actualizarJuga(int j1,int j2){
        if (j1==Jugador.HUMANO)
            jLabelJug1.setText("Humano");
        else{
            if (j1 == OthelloHexagonal.FACIL)
                jLabelJug1.setText("Maquina-Principiante");
            if (j1 == OthelloHexagonal.MEDIO)
                jLabelJug1.setText("Maquina-Normal)");
            if (j1 == OthelloHexagonal.EXPERTO)
                jLabelJug1.setText("Maquina-Experto)");
        }
        if (j2==Jugador.HUMANO)
            jLabelJug2.setText("Humano");
        else{
            if (j2 == OthelloHexagonal.FACIL)
                jLabelJug2.setText("Maquina-Principiante");
            if (j2 == OthelloHexagonal.MEDIO)
                jLabelJug2.setText("Maquina-Normal");
            if (j2 == OthelloHexagonal.EXPERTO)
                jLabelJug2.setText("Maquina-Experto");
        }
    }

    private void nuevoJuego(){
        if(conf.isVerd()){
            //otheHex = new OthelloHexagonal(conf.getValorSpin(), OthelloHexagonal.HUMANO, OthelloHexagonal.FICHA_BLANCA);
            OthelloConfig otc = conf.getOthCon();
            otheHex = new OthelloHexagonal(otc.getTamTab(), otc.getJug1(), otc.getJug2());
            actualizarJuga(otc.getJug1(), otc.getJug2());
            juegoTerm = false;
            jPanelJuego.removeAll();
            cargarPanelJuego();
            System.out.println("se reconocio cambio de othelo "+otc.getTamTab());
            conf.setVerd(false);
            if(otheHex.getTipoJug1() == Jugador.HUMANO)
                jLabelIcon1.setIcon(new ImageIcon(getClass().getResource("/icons/user.png")));
            else
                jLabelIcon1.setIcon(new ImageIcon(getClass().getResource("/icons/computer.png")));
            if(otheHex.getTipoJug2() == Jugador.HUMANO)
                jLabelIcon2.setIcon(new ImageIcon(getClass().getResource("/icons/user.png")));
            else
                jLabelIcon2.setIcon(new ImageIcon(getClass().getResource("/icons/computer.png")));
        }
    }
    // </editor-fold>

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    private JPanelOtelo jpaneJuegoHexagonal;
    private JDialogConfiguracion conf;
    private OthelloHexagonal otheHex;
    private boolean juegoTerm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFichasBlancas;
    private javax.swing.JLabel jLabelFichasNegras;
    private javax.swing.JLabel jLabelFichasTotales;
    private javax.swing.JLabel jLabelIcon1;
    private javax.swing.JLabel jLabelIcon2;
    private javax.swing.JLabel jLabelJug1;
    private javax.swing.JLabel jLabelJug2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelJuego;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPaneSuperior;
    // End of variables declaration//GEN-END:variables

}
